### ISSUE TITLE
可以尝试下数据吗

### ISSUE THREAD

**Issue by Endinlee** [ZHANGZ1YUE/RainGAN#1]
可以尝试下数据吗

**Comment by ZHANGZ1YUE** [comment]
I'm sorry but the data we're using is from Japanese Ministry MLIT, which requires to be applied individually on this [site](https://diasjp.net/service/xrain/). I am not allowed to share the dataset therefore. But I believe it should be really straightforward to implement on your own dataset, as it takes converted Numpy array of radar image with dimension 192 * 128 as standard.
